# Generated by Django 5.0.7 on 2024-08-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
