# Generated by Django 5.0.7 on 2024-08-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'Контактс',
                'verbose_name_plural': 'Контактсы',
            },
        ),
    ]
